/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DisplayHUD: typeof import('./src/components/DisplayHUD.vue')['default']
    FleecaJob: typeof import('./src/components/FleecaJob.vue')['default']
  }
}
